// <auto-generated>
//     Generated by code/tools/generar-recursos.py from Diccionario-i18n-Torres.xlsx.
//     Do not edit by hand: change the dictionary and generate this file again.
// </auto-generated>

namespace Torres.Client.Localization
{
    internal static class TextKeys
    {
        internal static class Common
        {
            internal const string WindowTitle = "Common.WindowTitle";
            internal const string GameName = "Common.GameName";
            internal const string ConnectedStatus = "Common.ConnectedStatus";
            internal const string ConnectingStatus = "Common.ConnectingStatus";
            internal const string OfflineStatus = "Common.OfflineStatus";
            internal const string LogInButton = "Common.LogInButton";
            internal const string ProfileMenuItem = "Common.ProfileMenuItem";
            internal const string RegisteredRole = "Common.RegisteredRole";
            internal const string GuestRole = "Common.GuestRole";
            internal const string ServerErrorTitle = "Common.ServerErrorTitle";
            internal const string ServerErrorDetail = "Common.ServerErrorDetail";
            internal const string RetryButton = "Common.RetryButton";
            internal const string ExitButton = "Common.ExitButton";
            internal const string BackButton = "Common.BackButton";
            internal const string BackToMenuButton = "Common.BackToMenuButton";
            internal const string BackToRoomButton = "Common.BackToRoomButton";
            internal const string CancelButton = "Common.CancelButton";
            internal const string GotItButton = "Common.GotItButton";
            internal const string YouTag = "Common.YouTag";
            internal const string GuestTag = "Common.GuestTag";
            internal const string DisconnectedTag = "Common.DisconnectedTag";
            internal const string WithdrewTag = "Common.WithdrewTag";
        }

        internal static class Startup
        {
            internal const string ConnectingStatus = "Startup.ConnectingStatus";
            internal const string ReadyStatus = "Startup.ReadyStatus";
        }

        internal static class MainMenu
        {
            internal const string HeaderLabel = "MainMenu.HeaderLabel";
            internal const string RoomsButton = "MainMenu.RoomsButton";
            internal const string InvitationsButton = "MainMenu.InvitationsButton";
            internal const string FriendsButton = "MainMenu.FriendsButton";
            internal const string HistoryButton = "MainMenu.HistoryButton";
            internal const string RankingButton = "MainMenu.RankingButton";
            internal const string ExitButton = "MainMenu.ExitButton";
            internal const string LanguageButton = "MainMenu.LanguageButton";
        }

        internal static class Language
        {
            internal const string HeaderLabel = "Language.HeaderLabel";
            internal const string Title = "Language.Title";
            internal const string Hint = "Language.Hint";
            internal const string SpanishOption = "Language.SpanishOption";
            internal const string EnglishOption = "Language.EnglishOption";
            internal const string SavedHint = "Language.SavedHint";
        }

        internal static class Login
        {
            internal const string HeaderLabel = "Login.HeaderLabel";
            internal const string Title = "Login.Title";
            internal const string Hint = "Login.Hint";
            internal const string UsernameLabel = "Login.UsernameLabel";
            internal const string PasswordLabel = "Login.PasswordLabel";
            internal const string InvalidCredentials = "Login.InvalidCredentials";
            internal const string AccountBannedTitle = "Login.AccountBannedTitle";
            internal const string AccountBannedDetail = "Login.AccountBannedDetail";
            internal const string LogInButton = "Login.LogInButton";
            internal const string CreateAccountButton = "Login.CreateAccountButton";
            internal const string ForgotAccessLink = "Login.ForgotAccessLink";
            internal const string PlayAsGuestLink = "Login.PlayAsGuestLink";
        }

        internal static class Register
        {
            internal const string HeaderLabel = "Register.HeaderLabel";
            internal const string Title = "Register.Title";
            internal const string Hint = "Register.Hint";
            internal const string UsernameLabel = "Register.UsernameLabel";
            internal const string UsernameAvailable = "Register.UsernameAvailable";
            internal const string UsernameUnavailable = "Register.UsernameUnavailable";
            internal const string EmailLabel = "Register.EmailLabel";
            internal const string EmailAlreadyExists = "Register.EmailAlreadyExists";
            internal const string PasswordLabel = "Register.PasswordLabel";
            internal const string CreateAccountButton = "Register.CreateAccountButton";
        }

        internal static class PasswordRecovery
        {
            internal const string HeaderLabel = "PasswordRecovery.HeaderLabel";
            internal const string Step1Title = "PasswordRecovery.Step1Title";
            internal const string Step1Hint = "PasswordRecovery.Step1Hint";
            internal const string EmailLabel = "PasswordRecovery.EmailLabel";
            internal const string InvalidEmail = "PasswordRecovery.InvalidEmail";
            internal const string SendCodeButton = "PasswordRecovery.SendCodeButton";
            internal const string Step2Title = "PasswordRecovery.Step2Title";
            internal const string Step2Hint = "PasswordRecovery.Step2Hint";
            internal const string CodeLabel = "PasswordRecovery.CodeLabel";
            internal const string InvalidCode = "PasswordRecovery.InvalidCode";
            internal const string VerifyButton = "PasswordRecovery.VerifyButton";
            internal const string Step3Title = "PasswordRecovery.Step3Title";
            internal const string Step3Hint = "PasswordRecovery.Step3Hint";
            internal const string NewPasswordLabel = "PasswordRecovery.NewPasswordLabel";
            internal const string RepeatPasswordLabel = "PasswordRecovery.RepeatPasswordLabel";
            internal const string SaveButton = "PasswordRecovery.SaveButton";
            internal const string BackToLoginButton = "PasswordRecovery.BackToLoginButton";
        }

        internal static class GuestAccess
        {
            internal const string HeaderLabel = "GuestAccess.HeaderLabel";
            internal const string Title = "GuestAccess.Title";
            internal const string Hint = "GuestAccess.Hint";
            internal const string MatchNameLabel = "GuestAccess.MatchNameLabel";
            internal const string RepeatableName = "GuestAccess.RepeatableName";
            internal const string Limitations = "GuestAccess.Limitations";
            internal const string EnterButton = "GuestAccess.EnterButton";
        }

        internal static class Profile
        {
            internal const string HeaderLabel = "Profile.HeaderLabel";
            internal const string ChangeAvatarButton = "Profile.ChangeAvatarButton";
            internal const string AvatarFormatHint = "Profile.AvatarFormatHint";
            internal const string AvatarMissing = "Profile.AvatarMissing";
            internal const string AvatarTooLarge = "Profile.AvatarTooLarge";
            internal const string AccountTitle = "Profile.AccountTitle";
            internal const string AccountHint = "Profile.AccountHint";
            internal const string UsernameLabel = "Profile.UsernameLabel";
            internal const string UsernameUnavailable = "Profile.UsernameUnavailable";
            internal const string EmailLabel = "Profile.EmailLabel";
            internal const string SaveButton = "Profile.SaveButton";
            internal const string AccountSettingsButton = "Profile.AccountSettingsButton";
        }

        internal static class AccountSettings
        {
            internal const string HeaderLabel = "AccountSettings.HeaderLabel";
            internal const string DeleteAccountTitle = "AccountSettings.DeleteAccountTitle";
            internal const string DeleteAccountHint = "AccountSettings.DeleteAccountHint";
            internal const string DeleteAccountButton = "AccountSettings.DeleteAccountButton";
            internal const string BackToProfileButton = "AccountSettings.BackToProfileButton";
        }

        internal static class Friends
        {
            internal const string HeaderLabel = "Friends.HeaderLabel";
            internal const string FriendsTab = "Friends.FriendsTab";
            internal const string ReceivedTab = "Friends.ReceivedTab";
            internal const string SentTab = "Friends.SentTab";
            internal const string SearchTab = "Friends.SearchTab";
            internal const string EmptyStateTitle = "Friends.EmptyStateTitle";
            internal const string EmptyStateHint = "Friends.EmptyStateHint";
            internal const string RemoveFriendButton = "Friends.RemoveFriendButton";
            internal const string RemoveFriendToolTip = "Friends.RemoveFriendToolTip";
            internal const string RequestsTitle = "Friends.RequestsTitle";
            internal const string FriendRequestMessage = "Friends.FriendRequestMessage";
            internal const string AcceptButton = "Friends.AcceptButton";
            internal const string RejectButton = "Friends.RejectButton";
            internal const string NoReceivedTitle = "Friends.NoReceivedTitle";
            internal const string NoReceivedHint = "Friends.NoReceivedHint";
            internal const string AwaitingResponseMessage = "Friends.AwaitingResponseMessage";
            internal const string PendingStatus = "Friends.PendingStatus";
            internal const string NoSentTitle = "Friends.NoSentTitle";
            internal const string NoSentHint = "Friends.NoSentHint";
            internal const string SearchPlaceholder = "Friends.SearchPlaceholder";
            internal const string SearchButton = "Friends.SearchButton";
            internal const string SendRequestButton = "Friends.SendRequestButton";
            internal const string AlreadyFriendsStatus = "Friends.AlreadyFriendsStatus";
            internal const string RequestSentStatus = "Friends.RequestSentStatus";
            internal const string RequestReceivedStatus = "Friends.RequestReceivedStatus";
            internal const string SelfExcludedHint = "Friends.SelfExcludedHint";
            internal const string NoResultsTitle = "Friends.NoResultsTitle";
            internal const string NoResultsHint = "Friends.NoResultsHint";
        }

        internal static class Invitations
        {
            internal const string HeaderLabel = "Invitations.HeaderLabel";
            internal const string EmptyStateTitle = "Invitations.EmptyStateTitle";
            internal const string EmptyStateHint = "Invitations.EmptyStateHint";
            internal const string InvitedByMessage = "Invitations.InvitedByMessage";
            internal const string RoomLabel = "Invitations.RoomLabel";
            internal const string JoinButton = "Invitations.JoinButton";
            internal const string RejectToolTip = "Invitations.RejectToolTip";
        }

        internal static class InvitePlayers
        {
            internal const string HeaderLabel = "InvitePlayers.HeaderLabel";
            internal const string MyFriendsTab = "InvitePlayers.MyFriendsTab";
            internal const string SearchByUsernameTab = "InvitePlayers.SearchByUsernameTab";
            internal const string InvitedBadge = "InvitePlayers.InvitedBadge";
            internal const string InviteButton = "InvitePlayers.InviteButton";
            internal const string InviteByEmailButton = "InvitePlayers.InviteByEmailButton";
        }

        internal static class History
        {
            internal const string HeaderLabel = "History.HeaderLabel";
            internal const string EmptyStateTitle = "History.EmptyStateTitle";
            internal const string EmptyStateHint = "History.EmptyStateHint";
            internal const string DateColumn = "History.DateColumn";
            internal const string PlayersColumn = "History.PlayersColumn";
            internal const string OpponentsColumn = "History.OpponentsColumn";
            internal const string RankColumn = "History.RankColumn";
            internal const string PointsColumn = "History.PointsColumn";
            internal const string ResultColumn = "History.ResultColumn";
            internal const string FinishedStatus = "History.FinishedStatus";
            internal const string ForfeitedStatus = "History.ForfeitedStatus";
            internal const string InterruptedStatus = "History.InterruptedStatus";
            internal const string GuestOpponentMessage = "History.GuestOpponentMessage";
            internal const string GuestOpponentsMessage = "History.GuestOpponentsMessage";
        }

        internal static class MatchDetail
        {
            internal const string HeaderLabel = "MatchDetail.HeaderLabel";
            internal const string SummaryLabel = "MatchDetail.SummaryLabel";
            internal const string RankColumn = "MatchDetail.RankColumn";
            internal const string PlayerColumn = "MatchDetail.PlayerColumn";
            internal const string PointsColumn = "MatchDetail.PointsColumn";
            internal const string BackToHistoryButton = "MatchDetail.BackToHistoryButton";
        }

        internal static class GlobalRanking
        {
            internal const string HeaderLabel = "GlobalRanking.HeaderLabel";
            internal const string EmptyStateTitle = "GlobalRanking.EmptyStateTitle";
            internal const string EmptyStateHint = "GlobalRanking.EmptyStateHint";
            internal const string RowNumberColumn = "GlobalRanking.RowNumberColumn";
            internal const string PlayerColumn = "GlobalRanking.PlayerColumn";
            internal const string WinsColumn = "GlobalRanking.WinsColumn";
            internal const string PointsColumn = "GlobalRanking.PointsColumn";
            internal const string MatchesColumn = "GlobalRanking.MatchesColumn";
        }

        internal static class Rooms
        {
            internal const string HeaderLabel = "Rooms.HeaderLabel";
            internal const string SearchPlaceholder = "Rooms.SearchPlaceholder";
            internal const string SearchButton = "Rooms.SearchButton";
            internal const string CreateRoomButton = "Rooms.CreateRoomButton";
            internal const string AvailableRoomsTitle = "Rooms.AvailableRoomsTitle";
            internal const string PublicOnlyBadge = "Rooms.PublicOnlyBadge";
            internal const string RefreshButton = "Rooms.RefreshButton";
            internal const string OccupancyBadge = "Rooms.OccupancyBadge";
            internal const string JoinButton = "Rooms.JoinButton";
            internal const string FullButton = "Rooms.FullButton";
            internal const string EmptyStateTitle = "Rooms.EmptyStateTitle";
            internal const string EmptyStateHint = "Rooms.EmptyStateHint";
            internal const string PrivateRoomsHint = "Rooms.PrivateRoomsHint";
        }

        internal static class CreateRoom
        {
            internal const string HeaderLabel = "CreateRoom.HeaderLabel";
            internal const string Title = "CreateRoom.Title";
            internal const string Hint = "CreateRoom.Hint";
            internal const string PublicOption = "CreateRoom.PublicOption";
            internal const string PublicOptionHint = "CreateRoom.PublicOptionHint";
            internal const string PrivateOption = "CreateRoom.PrivateOption";
            internal const string PrivateOptionHint = "CreateRoom.PrivateOptionHint";
            internal const string SharedRulesHint = "CreateRoom.SharedRulesHint";
            internal const string CreateRoomButton = "CreateRoom.CreateRoomButton";
        }

        internal static class Room
        {
            internal const string HeaderLabel = "Room.HeaderLabel";
            internal const string CopyButton = "Room.CopyButton";
            internal const string PublicBadge = "Room.PublicBadge";
            internal const string PrivateBadge = "Room.PrivateBadge";
            internal const string InvitePlayersButton = "Room.InvitePlayersButton";
            internal const string LeaveButton = "Room.LeaveButton";
            internal const string StartMatchButton = "Room.StartMatchButton";
            internal const string PlayersTitle = "Room.PlayersTitle";
            internal const string OccupancyLabel = "Room.OccupancyLabel";
            internal const string ActiveCountLabel = "Room.ActiveCountLabel";
            internal const string DisconnectedStatus = "Room.DisconnectedStatus";
            internal const string GuestBadge = "Room.GuestBadge";
            internal const string HostBadge = "Room.HostBadge";
            internal const string RemovePlayerToolTip = "Room.RemovePlayerToolTip";
            internal const string HostOnlyHint = "Room.HostOnlyHint";
            internal const string RoomRankingTitle = "Room.RoomRankingTitle";
            internal const string EmptyRankingTitle = "Room.EmptyRankingTitle";
            internal const string EmptyRankingHint = "Room.EmptyRankingHint";
        }

        internal static class Chat
        {
            internal const string NoMessages = "Chat.NoMessages";
            internal const string InputPlaceholder = "Chat.InputPlaceholder";
            internal const string ReportToolTip = "Chat.ReportToolTip";
        }

        internal static class Alerts
        {
            internal const string HeaderLabel = "Alerts.HeaderLabel";
            internal const string LeaveRoomTitle = "Alerts.LeaveRoomTitle";
            internal const string LeaveRoomBody = "Alerts.LeaveRoomBody";
            internal const string LeaveConfirmButton = "Alerts.LeaveConfirmButton";
            internal const string StayButton = "Alerts.StayButton";
            internal const string DeleteAccountTitle = "Alerts.DeleteAccountTitle";
            internal const string DeleteAccountBody = "Alerts.DeleteAccountBody";
            internal const string DeleteConfirmButton = "Alerts.DeleteConfirmButton";
            internal const string RoomNotFoundTitle = "Alerts.RoomNotFoundTitle";
            internal const string RoomNotFoundBody = "Alerts.RoomNotFoundBody";
            internal const string RoomFullTitle = "Alerts.RoomFullTitle";
            internal const string RoomFullBody = "Alerts.RoomFullBody";
            internal const string ViewRoomsButton = "Alerts.ViewRoomsButton";
            internal const string RemovePlayerTitle = "Alerts.RemovePlayerTitle";
            internal const string RemovePlayerBody = "Alerts.RemovePlayerBody";
            internal const string RemoveConfirmButton = "Alerts.RemoveConfirmButton";
            internal const string RemovedFromRoomTitle = "Alerts.RemovedFromRoomTitle";
            internal const string RemovedFromRoomBody = "Alerts.RemovedFromRoomBody";
            internal const string SuspensionTitle = "Alerts.SuspensionTitle";
            internal const string SuspensionBody = "Alerts.SuspensionBody";
            internal const string RemoveFriendTitle = "Alerts.RemoveFriendTitle";
            internal const string RemoveFriendBody = "Alerts.RemoveFriendBody";
            internal const string ForfeitTitle = "Alerts.ForfeitTitle";
            internal const string ForfeitBody = "Alerts.ForfeitBody";
            internal const string ForfeitConfirmButton = "Alerts.ForfeitConfirmButton";
            internal const string EmailFailedTitle = "Alerts.EmailFailedTitle";
            internal const string EmailFailedBody = "Alerts.EmailFailedBody";
        }

        internal static class MatchPreparation
        {
            internal const string HeaderLabel = "MatchPreparation.HeaderLabel";
            internal const string Title = "MatchPreparation.Title";
            internal const string SummaryLabel = "MatchPreparation.SummaryLabel";
            internal const string SeatingOrderLabel = "MatchPreparation.SeatingOrderLabel";
        }

        internal static class InitialPlacement
        {
            internal const string HeaderLabel = "InitialPlacement.HeaderLabel";
            internal const string PlayersLabel = "InitialPlacement.PlayersLabel";
            internal const string TurnOrderLabel = "InitialPlacement.TurnOrderLabel";
            internal const string PlaceCaterpillarInstruction = "InitialPlacement.PlaceCaterpillarInstruction";
            internal const string CurrentTurnInstruction = "InitialPlacement.CurrentTurnInstruction";
        }

        internal static class Match
        {
            internal const string HeaderLabel = "Match.HeaderLabel";
            internal const string PlayersLabel = "Match.PlayersLabel";
            internal const string YourCaterpillarsLabel = "Match.YourCaterpillarsLabel";
            internal const string BuildingsLabel = "Match.BuildingsLabel";
            internal const string RoundTurnInstruction = "Match.RoundTurnInstruction";
            internal const string YourTurnStatus = "Match.YourTurnStatus";
            internal const string OtherPlayerTurnStatus = "Match.OtherPlayerTurnStatus";
            internal const string CaterpillarActionButton = "Match.CaterpillarActionButton";
            internal const string MoveActionButton = "Match.MoveActionButton";
            internal const string GrowActionButton = "Match.GrowActionButton";
            internal const string BuildActionButton = "Match.BuildActionButton";
            internal const string DeckLabel = "Match.DeckLabel";
            internal const string DrawButton = "Match.DrawButton";
            internal const string EndTurnButton = "Match.EndTurnButton";
            internal const string MatchLabel = "Match.MatchLabel";
            internal const string ForfeitButton = "Match.ForfeitButton";
            internal const string ActionPointsLabel = "Match.ActionPointsLabel";
        }

        internal static class RoundSummary
        {
            internal const string HeaderLabel = "RoundSummary.HeaderLabel";
            internal const string RoundFinishedTitle = "RoundSummary.RoundFinishedTitle";
            internal const string GardenStaysInstruction = "RoundSummary.GardenStaysInstruction";
            internal const string PlayerColumn = "RoundSummary.PlayerColumn";
            internal const string PlantersColumn = "RoundSummary.PlantersColumn";
            internal const string ButterflyColumn = "RoundSummary.ButterflyColumn";
            internal const string RoundColumn = "RoundSummary.RoundColumn";
            internal const string PlaceButterflyInstruction = "RoundSummary.PlaceButterflyInstruction";
            internal const string Round3RulesInstruction = "RoundSummary.Round3RulesInstruction";
        }

        internal static class Result
        {
            internal const string HeaderLabel = "Result.HeaderLabel";
            internal const string WinnerTitle = "Result.WinnerTitle";
            internal const string SummaryLabel = "Result.SummaryLabel";
            internal const string PlayerColumn = "Result.PlayerColumn";
            internal const string PlantersColumn = "Result.PlantersColumn";
            internal const string ButterflyColumn = "Result.ButterflyColumn";
            internal const string CardsColumn = "Result.CardsColumn";
            internal const string TotalColumn = "Result.TotalColumn";
            internal const string RoomStillOpenHint = "Result.RoomStillOpenHint";
        }

        internal static class Disconnection
        {
            internal const string HeaderLabel = "Disconnection.HeaderLabel";
            internal const string ConnectionLostTitle = "Disconnection.ConnectionLostTitle";
            internal const string ResumeTurnMessage = "Disconnection.ResumeTurnMessage";
            internal const string RetryButton = "Disconnection.RetryButton";
            internal const string ExitMatchButton = "Disconnection.ExitMatchButton";
            internal const string PlayersLabel = "Disconnection.PlayersLabel";
        }

        internal static class Resume
        {
            internal const string HeaderLabel = "Resume.HeaderLabel";
            internal const string Title = "Resume.Title";
            internal const string WaitingStatus = "Resume.WaitingStatus";
            internal const string NoActionNeededMessage = "Resume.NoActionNeededMessage";
        }

        internal static class MatchInProgress
        {
            internal const string HeaderLabel = "MatchInProgress.HeaderLabel";
            internal const string Title = "MatchInProgress.Title";
            internal const string LeftWhileOfflineMessage = "MatchInProgress.LeftWhileOfflineMessage";
            internal const string ReturnToMatchButton = "MatchInProgress.ReturnToMatchButton";
            internal const string AbandonButton = "MatchInProgress.AbandonButton";
            internal const string AbandonHint = "MatchInProgress.AbandonHint";
        }
    }
}
